# Generated by Django 4.0.4 on 2022-05-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_alter_comment_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='artical',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='travelapp.article'),
        ),
    ]
