# Generated by Django 4.0.3 on 2022-03-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_category_customer_department_tourguide_tour_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tours',
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ManyToManyField(to='travelapp.customer'),
        ),
    ]
