# Generated by Django 4.0.3 on 2022-03-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_remove_ticket_tours_ticket_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour', to='travelapp.tour'),
        ),
    ]
