# Generated by Django 4.0.3 on 2022-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_hotel_transport_tour_customer_arrival_tour_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='imageTourGuide',
            field=models.ImageField(blank=True, null=True, upload_to='imageTour/%Y/%m'),
        ),
    ]
