# Generated by Django 4.0.3 on 2022-03-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_tourguide_imagetourguide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name_tourguide',
            new_name='name_department',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='imageTour/%Y/%m'),
        ),
    ]
