# Generated by Django 4.0.3 on 2022-03-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_rename_name_tourguide_department_name_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name_department',
            field=models.CharField(max_length=50),
        ),
    ]
