# Generated by Django 4.0.3 on 2022-03-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='imageTour',
            field=models.ImageField(blank=True, null=True, upload_to='imageTour/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='tourguide',
            name='imageTourGuide',
            field=models.ImageField(blank=True, null=True, upload_to='imageTourGuide/%Y/%m'),
        ),
    ]
