# Generated by Django 4.0.3 on 2022-03-30 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_tour_imagetour_alter_tourguide_imagetourguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='iden',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourguide',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='seat',
            field=models.IntegerField(max_length=100),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('typr', models.PositiveSmallIntegerField(choices=[(0, '1 Star'), (1, '2 Star'), (2, '3 Star'), (3, '4 Star'), (4, '5 Star')], default=4)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.tour')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Like'), (1, 'Not like')], default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.tour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
