# Generated by Django 4.0.3 on 2022-03-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0012_alter_department_phone_alter_tour_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourguide',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='seat',
            field=models.IntegerField(),
        ),
    ]
