# Generated by Django 3.2.5 on 2022-04-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0016_rename_customer_ticket_customers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
