# Generated by Django 4.0.4 on 2022-04-27 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0019_comment_like_tag_usertourview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'like'), (1, 'haha'), (2, 'heart')], default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TourView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='department',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='department',
        ),
        migrations.AlterUniqueTogether(
            name='usertourview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertourview',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='usertourview',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='lesson',
            new_name='tour',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='imageTour',
            new_name='image',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='active',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='arrivals',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='hotels',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tourguide',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='transports',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='viewers',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tours', to='travelapp.tag'),
        ),
        migrations.AlterModelTable(
            name='tour',
            table='tour',
        ),
        migrations.DeleteModel(
            name='Arrival',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TourGuide',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.DeleteModel(
            name='UserTourView',
        ),
        migrations.AddField(
            model_name='tourview',
            name='tour',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travelapp.tour'),
        ),
        migrations.AddField(
            model_name='action',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.tour'),
        ),
    ]
