# Generated by Django 4.0.4 on 2022-04-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0020_action_tourview_alter_like_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
