# Generated by Django 4.0.4 on 2022-04-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0022_tour_category_alter_tour_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_date',
        ),
    ]
