# Generated by Django 4.0.4 on 2022-04-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0023_remove_category_active_remove_category_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={},
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelapp.category'),
        ),
        migrations.AlterModelTable(
            name='tour',
            table=None,
        ),
    ]
