# Generated by Django 4.0.4 on 2022-04-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0025_alter_tour_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('tour', 'creator')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('tour', 'creator')},
        ),
        migrations.RemoveField(
            model_name='action',
            name='active',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='active',
        ),
    ]
