# Generated by Django 4.0.4 on 2022-05-02 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0027_customer_department_hotel_tourguide_transport_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='content',
        ),
        migrations.AddField(
            model_name='tourguide',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Department', to='travelapp.department'),
        ),
    ]
