# Generated by Django 4.0.4 on 2022-05-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0028_remove_tour_content_tourguide_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
        migrations.AddField(
            model_name='tour',
            name='imageTour',
            field=models.ImageField(blank=True, null=True, upload_to='imageTour/%Y/%m'),
        ),
    ]
